In [14]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [2]:
data = pd.read_csv("class_example.csv")

In [3]:
data

sq_area  age   price
0     1500    5  102.00
1     1200    8   75.00
2     1369    5   86.00
3     1458    2   89.50
4     2589    0   45.20
5     2456    9   98.36
6      800    4  205.00

In [5]:
data_as_numpy = data.values

In [7]:
type(data_as_numpy)

numpy.ndarray

In [8]:
data_as_numpy.shape

(7, 3)

In [9]:
data_as_numpy

array([[1.500e+03, 5.000e+00, 1.020e+02],
       [1.200e+03, 8.000e+00, 7.500e+01],
       [1.369e+03, 5.000e+00, 8.600e+01],
       [1.458e+03, 2.000e+00, 8.950e+01],
       [2.589e+03, 0.000e+00, 4.520e+01],
       [2.456e+03, 9.000e+00, 9.836e+01],
       [8.000e+02, 4.000e+00, 2.050e+02]])

In [10]:
X = data_as_numpy[:, 0:2]
y = data_as_numpy[:, 2]

In [11]:
X

array([[1.500e+03, 5.000e+00],
       [1.200e+03, 8.000e+00],
       [1.369e+03, 5.000e+00],
       [1.458e+03, 2.000e+00],
       [2.589e+03, 0.000e+00],
       [2.456e+03, 9.000e+00],
       [8.000e+02, 4.000e+00]])

In [12]:
y

array([102.  ,  75.  ,  86.  ,  89.5 ,  45.2 ,  98.36, 205.  ])

In [15]:
reg = LinearRegression().fit(X, y) #.fit means to find the parameters

In [17]:
reg.coef_

array([-0.04782857,  0.84285351])

In [18]:
reg.intercept_

173.87890215047938

In [ ]:
#y-hat = 173.8 -0.047.x1 + 0.84.x2 #ML model/solution

In [19]:
173.8 -0.047*1400 + 0.84*1

108.84000000000002