In [1]:
import numpy as np #np is an alias

In [3]:
ls1 = [1,2,3,4]
arr = np.array(ls1) #Converting a python list to numpy array

In [13]:
print(arr)

[1 2 3 4]


In [14]:
type(arr)

numpy.ndarray

In [15]:
arr.sum() #sum is a method defined inside numpy.array class

10

In [16]:
arr.shape #shape is an attribute defined inside numpy.array class

(4,)

In [17]:
arr.sum(), arr.shape

(10, (4,))

In [19]:
arr1 = np.array([1,2,3.5,'abc']) #Numpy arrays take homogeneous data unlike a python list
arr1

array(['1', '2', '3.5', 'abc'], dtype='<U32')

In [20]:
arr2 = np.array(['a', 'b'])
arr2

array(['a', 'b'], dtype='<U1')

In [4]:
arr3 = np.array([1,2,3.5])
arr3

array([1. , 2. , 3.5])

In [2]:
arr4 = numpy.array([1,2,3])
print(arr4)

NameError: ignored

In [5]:
arr3

array([1. , 2. , 3.5])

In [6]:
list(arr3)

[1.0, 2.0, 3.5]

In [7]:
tuple(arr3)

(1.0, 2.0, 3.5)

In [8]:
arr = np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [10]:
arr[-3]

40

In [12]:
arr[1:4:2] #Array slicing

array([20, 40])

In [13]:
arr.shape

(6,)

In [26]:
ls2 = [[1,2,3,4], [4,5,6, 7], [7,8,9,3]]
arr2 = np.array(ls2) #2D array = Matrix
arr2

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 3]])

In [30]:
arr2[1:-1, 1:-1]

array([[5, 6]])

In [29]:
# arr2[1:2:1, 0:4:3]
arr2[1, ::3]

array([4, 7])

In [22]:
# arr2[start:stop:step, start:stop:step]
arr2[:, 1:]

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 3]])

In [17]:
arr2.shape # arr2 has two axes axis0 and axis1

(3, 4)

In [25]:
arr = np.array([[[10,20,30,40,50,60]]])
print(arr)
print(arr.shape)

[[[10 20 30 40 50 60]]]
(1, 1, 6)


In [33]:
#Iterating numpy arrays
import numpy as np
arr1 = np.array(['a','b','c'])
ls2 = [[1,2,3,4], [4,5,6, 7], [7,8,9,3]]
arr2 = np.array(ls2) #2D array = Matrix
print(arr1)
print(arr2)

['a' 'b' 'c']
[[1 2 3 4]
 [4 5 6 7]
 [7 8 9 3]]


In [51]:
for row in range(3):
  for col in range(4):
    print(arr2[row, col], end=' ') #Indexing
  print("\n")

1 2 3 4 

4 5 6 7 

7 8 9 3 



In [46]:
x = 1
y = 2
z = 3
print(x, y, z, sep = "")


1abc2abc3


In [35]:
for i in range(len(arr1)):
  print(arr1[i])

a
b
c


In [34]:
for ele in arr1:
  print(ele)

a
b
c


In [56]:
#List comprehension
ls1 = [1,2,3,4,5]

In [58]:
ls2 = []
for ele in ls1:
  ls2.append(ele*2)

ls2

[2, 4, 6, 8, 10]

In [59]:
ls3 = [ele*2 for ele in ls1]
ls3

[2, 4, 6, 8, 10]