# 1. Write a program using list comprehension to find primes in range 2 to 100

In [1]:
consonants = [j for i in range(2, 8) for j in range(i*2, 100, i)] 
primes = [x for x in range(2, 100) if x not in consonants] 
print(primes)
print(len(primes))



[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
25


# 2. Write a function to reverse a string
*String = 'Data Science'*

In [13]:
def rev():
    s = str(input("Enter a String : "))
    rev_str = s[::-1]
    return rev_str


In [14]:
rev()

'tuor utiL'

# 3. Write a program to extract the words from the given list which have their first character in uppercase
*Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']*

*Output: ['Monday', 'Sunday', 'Saturday']*

In [18]:
Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']
Output = []
for name in Days:
    n_list = name.split()
    for i in range(len(n_list)):
        if n_list[i][0].isupper():
            Output.append(n_list[i])

print(Output)

['Monday', 'Sunday', 'Saturday']


# 4. Write a program to extract the year part from the dates in the given list
*Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']*

*Output: ['1997','2011','1993','2020']*

In [20]:
Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']
Year = []
for date in Batch:
    Year.append(date.split('-')[2])

print(Year)



['1997', '2011', '1993', '2020']


# 5. Write a program swap the keys to values and values to keys of the given dictionary

*Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4}*

*Output: {1:'Data Science',2:'Machine Learning', 3:'SQL', 4:'Big Data'}*


In [22]:
Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'Big Data':4}
New_module = dict([(value, key) for key, value in Module.items()])

print(New_module)


{1: 'Data Science', 2: 'Machine Learning', 3: 'SQL', 4: 'Big Data'}


# 6. Write a program to calculate the cumulative average of the given list using accumulate() and lambda function

*Input list: [5,2,1,4,6]*

In [7]:
from itertools import accumulate
Result = accumulate([5, 2, 1, 4, 6], lambda x, y: (x+y)/2)

for res in Result:
    print(res)

5
3.5
2.25
3.125
4.5625


# 7. Write a program to count the number of elements in the string (given by the user) that are not present in the 'my_string'. Do not count the white spaces

#### Use Recursion

*my_string = 'Data Science'*

3

# 8.  Define a function to check whether a number is in a range (1000,10000) or not

In [28]:
def inrange(n):
    if n in range(1000,10000):
        print("The Number is in range.")
    else:
        print("The number is not in range")

In [30]:
inrange(10001)

The number is not in range


# 9. Write a program to print pascal triangle upto 6 steps (using list)

In [31]:
list=[1]
for i in range(6):
    print(list)
    newlist=[]
    newlist.append(list[0])
    for i in range(len(list)-1):
        newlist.append(list[i]+list[i+1])
    newlist.append(list[-1])
    list=newlist

[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
[1, 5, 10, 10, 5, 1]


# 10. Write a program to calculate the sum of all elements in the list

*test_score = [10, 32, 23, 14, 25]*

In [1]:
ts = [10, 32, 23, 14, 25]

print(sum(ts))


104


# 11. Find the minimum value along each of the rows

Create a 2D Numpy array from list of lists<br>

Score = np.array([[210, 402, 383],<br>
                 [140, 375, 106], <br>
                 [140, 125, 217], <br>
                 [292, 240, 295]])

In [64]:
import numpy as np
Score = np.array([[210, 402, 383],
                 [140, 375, 106],
                 [140, 125, 217], 
                 [292, 240, 295]])

Score

array([[210, 402, 383],
       [140, 375, 106],
       [140, 125, 217],
       [292, 240, 295]])

In [66]:
min_value = np.amin(Score, axis=1)
min_value

array([210, 106, 125, 240])

# 12.  Replace all even numbers in the array with -1

Use the array given below

    num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [68]:
num_array = np.array([0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])
num_array

array([ 0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [72]:
num_array[num_array % 2 == 0] = -1
num_array


array([-1, 21, -1, 13, -1, 45, -1, -1, -1, -1, 65, -1, -1])

# 13. Create a pandas series having values 4, 8, -1, 2, NAN and their index as d, b, a, c, e

In [76]:
import pandas as pd

my_s = pd.Series([4, 8, -1, 2, np.nan], index=("d","b","a","c","e"))

my_s

d    4.0
b    8.0
a   -1.0
c    2.0
e    NaN
dtype: float64

# 14. Add a new column 'Height' in the give dataframe

<table>
  <tr>
  <th>Name </th>
  <th>Weight</th>
  </tr>
  <tr>
  <td>Mia</td>
  <td>55</td>    
  </tr>
  <tr>
  <td>Joy</td>
  <td>66</td> 
  </tr>
  <tr>
  <td>Karan</td>
  <td>80</td> 
  </tr>
  <tr>
  <td>George</td>
  <td>67</td> 
</tr>
</table>
  

New Column:
<table>
  <tr>
  <th>Height</th>   
  </tr>
  <tr>
  <td>5.5</td>
  </tr>
  <tr>
  <td>6.7</td>
  </tr>
  <tr>
  <td>5.8</td>
  </tr>
  <tr>
  <td>6</td>
</tr>
</table>

In [84]:
s = {"Name":["Mia","Joy","Karan","George"],  
     "Weight":[55, 66, 80, 67]}

Tb_1 = pd.DataFrame(s)
Tb_1

Name  Weight
0     Mia      55
1     Joy      66
2   Karan      80
3  George      67

In [85]:
Tb_1['Height'] = [5.5, 6.7, 5.8, 6]
print(Tb_1)

     Name  Weight  Height
0     Mia      55     5.5
1     Joy      66     6.7
2   Karan      80     5.8
3  George      67     6.0


# 15. Use the data created in question 14, to do the following:
Access column 'Name' by specifying the column number<br>
Access column 'Height' by specifying the column name

In [91]:
Tb_1.iloc[:,0]
Tb_1.iloc[:,2]

0    5.5
1    6.7
2    5.8
3    6.0
Name: Height, dtype: float64

In [92]:
Tb_1.Name

0       Mia
1       Joy
2     Karan
3    George
Name: Name, dtype: object

In [93]:
Tb_1.Height

0    5.5
1    6.7
2    5.8
3    6.0
Name: Height, dtype: float64

# 16. Find duplicate rows based on the column 'Order_ID'

**Use the dataframe given below:**
   
<table>
<tr>
<th>Order_ID</th>
<th>Product</th>
<th>City</th>
</tr>
<tr>
<td>YZ1100</td>
<td>Cell Phone</td>
<td>Sydeny</td>
</tr>
<tr>
<td>RW1200</td>
<td>Watch</td>
<td>Chicago</td>
</tr>
<tr>
<td>YZ1100</td>
<td>Cell Phone</td>
<td>New York</td>
</tr>
<tr>
<td>TY1400</td>
<td>Charger</td>
<td>Chicago</td>
</tr>
<tr>
<td>VB1500</td>
<td>Watch</td>
<td>Chicago</td>
</tr>
<tr>
<td>TY1400</td>
<td>Headphones</td>
<td>Texas</td>
</tr>
<tr>
<td>MW1600</td>
<td>Charger</td>
<td>New York</td>
</tr>
<tr>
<td>CN1600</td>
<td>Headphones</td>
<td>Chicago</td>
</tr>
   
</table>

In [96]:
p = [('YZ1100', 'Cell Phone', 'Sydeny'),
('RW1200', 'Watch', 'Chicago'),
('YZ1100', 'Cell Phone', 'New York'),
('TY1400', 'Charger', 'Chicago'),
('VB1500', 'Watch', 'Chicago'),
('TY1400', 'Headphones', 'Texas'),
('MW1600', 'Charger', 'New York'),
('CN1600', 'Headphones', 'Chicago')]

Tb_2 = pd.DataFrame(p)
Tb_2

0           1         2
0  YZ1100  Cell Phone    Sydeny
1  RW1200       Watch   Chicago
2  YZ1100  Cell Phone  New York
3  TY1400     Charger   Chicago
4  VB1500       Watch   Chicago
5  TY1400  Headphones     Texas
6  MW1600     Charger  New York
7  CN1600  Headphones   Chicago

In [98]:
d_rows = Tb_2[Tb_2.duplicated([0])]
d_rows

0           1         2
2  YZ1100  Cell Phone  New York
5  TY1400  Headphones     Texas

# 17. Use the data created in question 16, to do the following:
In column 'Product', replace all the 'Cell Phone' values with 'Mobile' using numpy.where


In [111]:
p = [('YZ1100', 'Cell Phone', 'Sydeny'),
('RW1200', 'Watch', 'Chicago'),
('YZ1100', 'Cell Phone', 'New York'),
('TY1400', 'Charger', 'Chicago'),
('VB1500', 'Watch', 'Chicago'),
('TY1400', 'Headphones', 'Texas'),
('MW1600', 'Charger', 'New York'),
('CN1600', 'Headphones', 'Chicago')]

Tb_3 = pd.DataFrame(p, columns= ['Order_ID', 'Products', 'City'])
Tb_3
Tb_3.replace(to_replace = "Cell Phone", value = "Mobile")

Order_ID    Products      City
0   YZ1100      Mobile    Sydeny
1   RW1200       Watch   Chicago
2   YZ1100      Mobile  New York
3   TY1400     Charger   Chicago
4   VB1500       Watch   Chicago
5   TY1400  Headphones     Texas
6   MW1600     Charger  New York
7   CN1600  Headphones   Chicago

In [112]:
Tb_3.replace(to_replace = "Cell Phone", value = "Mobile")

Order_ID    Products      City
0   YZ1100      Mobile    Sydeny
1   RW1200       Watch   Chicago
2   YZ1100      Mobile  New York
3   TY1400     Charger   Chicago
4   VB1500       Watch   Chicago
5   TY1400  Headphones     Texas
6   MW1600     Charger  New York
7   CN1600  Headphones   Chicago

# 18. Perform right join to combine values based on the 'ID' in the two dataframes

**Use the dataframe given below:**
   
<table>
    <tr>
        <th>ID</th>
        <th>Candidate_Name</th>
        <th>Subject</th>
    </tr>
    <tr>
        <td>101</td>
        <td>Alex</td>
        <td>History</td>
    </tr>
    <tr>
        <td>102</td>
        <td>Amy</td>
        <td>English</td>
    </tr>
    <tr>
        <td>103</td>
        <td>Allen</td>
        <td>Geography</td>
    </tr>
    <tr>
        <td>104</td>
        <td>Alice</td>
        <td>German</td>
    </tr>
        <td>105</td>
        <td>James</td>
        <td>History</td>
    </tr>
    <tr>
        <td>106</td>
        <td>Sara</td>
        <td>German</td>
    </tr>
    <tr>
        <td>107</td>
        <td>Mia</td>
        <td>English</td>
    </tr>  
</table>
<br>



<table>
    <tr>
        <th>ID</th>
        <th>City</th>
        <th>Subject_Score</th>
    </tr>
    <tr>
        <td>101</td>
        <td>Delhi</td>
        <td>89</td>
    </tr>
    <tr>
        <td>102</td>
        <td>Mumbai</td>
        <td>78</td>
    </tr>
    <tr>
        <td>103</td>
        <td>Delhi</td>
        <td>77</td>
    </tr>
    <tr>
        <td>104</td>
        <td>Chennai</td>
        <td>87</td>
    </tr>
    <tr>
        <td>105</td>
        <td>Hyderabad</td>
        <td>87</td>
    </tr>
        <td>108</td>
        <td>Delhi</td>
        <td>84</td>

    </tr>
</table>

In [113]:

Info_1 = pd.DataFrame({
'ID':[101,102,103,104,105,106,107],
'Candidate_Name': ['Alex', 'Amy', 'Allen', 'Alice', 'James', 'Sara', 'Mia'],
'Subject':['History','English','Geography','German','History', 'German', 'English']})

Info_2 = pd.DataFrame(
{'ID':[101,102,103,104,105,108],
'City': ['Delhi', 'Mumbai', 'Delhi', 'Chennai', 'Hyderabad','Delhi'],
'Subject_Score':[89,78,77,87,87,84]})

# print the data
print(Info_1,'\n')
print(Info_2)

    ID Candidate_Name    Subject
0  101           Alex    History
1  102            Amy    English
2  103          Allen  Geography
3  104          Alice     German
4  105          James    History
5  106           Sara     German
6  107            Mia    English 

    ID       City  Subject_Score
0  101      Delhi             89
1  102     Mumbai             78
2  103      Delhi             77
3  104    Chennai             87
4  105  Hyderabad             87
5  108      Delhi             84


In [117]:
r_join = pd.merge(Info_1, Info_2, on=['ID'], how='right')
r_join

ID Candidate_Name    Subject       City  Subject_Score
0  101           Alex    History      Delhi             89
1  102            Amy    English     Mumbai             78
2  103          Allen  Geography      Delhi             77
3  104          Alice     German    Chennai             87
4  105          James    History  Hyderabad             87
5  108            NaN        NaN      Delhi             84

# 19. Use the following data to plot a pie chart and annotate the percentage sales

<table>
    <tr>
        <th>City</th>
        <th>Sales</th>
    </tr>
    <tr>
        <td>Delhi</td>
        <td>890</td>
    </tr>
    <tr>
        <td>Mumbai</td>
        <td>784</td>
    </tr>
    <tr>
        <td>Delhi</td>
        <td>775</td>
    </tr>
    <tr>
        <td>Chennai</td>
        <td>873</td>
    </tr>
    <tr>
        <td>Hyderabad</td>
        <td>387</td>
    </tr>
        <td>Delhi</td>
        <td>684</td>

    </tr>
</table>

In [121]:
import matplotlib.pyplot as plt

sales = np.array([890, 784,775, 873, 387, 684])
city = ['Delhi','Mumbai','Delhi','Chennai',"Hyderabad","Delhi"]

D = pd.DataFrame(sales, city)
D

0
Delhi      890
Mumbai     784
Delhi      775
Chennai    873
Hyderabad  387
Delhi      684

In [129]:
plt.pie(sales, autopct='%1.1f%%')
plt.title('Percentage sales' )

Text(0.5, 1.0, 'Percentage sales')

# 20. Use the data created in question 19, to do the following:
Calculate minimum, maximum and average sales for each origin

In [133]:
Q20 = pd.DataFrame({'City': ['Delhi','Mumbai','Delhi','Chennai',"Hyderabad","Delhi"],
'Sales': [890, 784,775, 873, 387, 684]})

Q20

City  Sales
0      Delhi    890
1     Mumbai    784
2      Delhi    775
3    Chennai    873
4  Hyderabad    387
5      Delhi    684

In [138]:
Tb_20 = Q20.groupby('City').agg({'Sales':['min','max','mean']})
Tb_20

Sales            
            min  max   mean
City                       
Chennai     873  873  873.0
Delhi       684  890  783.0
Hyderabad   387  387  387.0
Mumbai      784  784  784.0